### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by gabrieru** [keynertyc/click-to-call#1]
i added clicktocall2.conf info to extensions.conf and added the php file to var/www/html/caller then i tried to call but i dont know how to do it, its ok 

http://192.168.0.10/Llamar/sendcall.php?extension=10&phone=10 ?

where my phone is SIP and number 12

**Comment by keynertyc** [comment]
Have you restarted your asterisk services?

- set CalledId in file.php

click2call.php receive 2 parameters: extension and phone to call.

extension: you have to create a IAX2 extension in asterisk
phone: phone to call with i.e: +13548728374

you have to include click2call.conf in your asterisk.

then reload: core reload 

click2call.php send the request to the asterisk context click2call

context "click2call":

exten => s,1,Dial(SIP/VoIpTrunk/${phone})  => replace VoIpTrunk with your name of trunk to make outbound calls. i.e twilio or some else provider.
